-- =========================================================================
-- vuln_scripts_cleaned.sql
-- Auto-generated by front-end/scripts/generate-vuln-scripts-cleanup.js
-- Generated 2026-04-24T02:17:46.865Z
-- Run this AFTER importing vuln_scripts (1).sql.
--
-- PART 1: UPDATE metadata on existing rows (script_content untouched).
-- PART 2: INSERT 13 new Phase-1 scripts (idempotent via ON CONFLICT).
-- =========================================================================
BEGIN;

-- ---------- PART 1: metadata cleanup on existing rows ----------

UPDATE vuln_scripts SET
  name                  = 'DunderCorp Artifacts (Users/Ops)',
  description           = 'Seeds realistic user + ops artifacts under C:\ProgramData\DunderCorp\Artifacts (Creds/Logs/Configs/Exports/Notes/Transcripts) plus USER2/ADMIN PSReadLine history and LabShare drops. Supports -Setup, -Verify, and -Reset.',
  category              = 'User Simulation',
  difficulty            = 'intermediate',
  services_exposed      = '[]'::jsonb,
  script_type           = 'baseline',
  estimated_runtime_sec = 60,
  script_args           = '-Setup'
WHERE slug = 'win-artifact';

UPDATE vuln_scripts SET
  name                  = 'WinRM Insecure Exposure',
  description           = 'Enables PSRemoting, sets WinRM to autostart, and adds a non-admin (default USER2) to Remote Management Users. Default path: HTTP listener on 5985. With -EnableHttps: self-signed cert + HTTPS listener on 5986 + firewall rule. Intended for vuln-lab use; not a hardened baseline.',
  category              = 'Network Services',
  difficulty            = 'intermediate',
  services_exposed      = '["5985/WinRM","5986/WinRM-HTTPS"]'::jsonb,
  script_type           = 'vulnerable',
  estimated_runtime_sec = 30,
  script_args           = ''
WHERE slug = 'winrm';

UPDATE vuln_scripts SET
  name                  = 'SMB (Null Session Enabled)',
  description           = 'Provisions the Public/Users/Drop/Legacy SMB share layout and explicitly enables null-session access (RestrictNullSessAccess=0, RestrictAnonymous=0, NullSessionShares=Public) so unauthenticated enumeration of shares and pipes is possible. Seeds share content for discovery.',
  category              = 'Network Services',
  difficulty            = 'beginner',
  services_exposed      = '["445/SMB"]'::jsonb,
  script_type           = 'vulnerable',
  estimated_runtime_sec = 30,
  script_args           = ''
WHERE slug = 'win-smb-null-session';

UPDATE vuln_scripts SET
  name                  = 'DunderCorp Persistence Trio',
  description           = 'Creates three persistence artifacts: HKLM Run entry DunderOpsUpdate (wscript.exe opshelper.vbs), Startup-folder CMD DunderStartup.cmd, and SYSTEM scheduled task DunderUserEnvSync (userenv_sync.ps1 on-logon). Stages supporting files under C:\ProgramData\DunderCorp\Persistence with read-only ACLs; supports -Verify and -Reset.',
  category              = 'Persistence',
  difficulty            = 'intermediate',
  services_exposed      = '[]'::jsonb,
  script_type           = 'vulnerable',
  estimated_runtime_sec = 45,
  script_args           = ''
WHERE slug = 'win-persistence';

UPDATE vuln_scripts SET
  name                  = 'DunderCorp Privilege Escalation Lab',
  description           = 'Two SYSTEM execution rails for privesc: scheduled task DunderCacheRefresh (refresh_cache.ps1 every minute as SYSTEM) and weak service DunderTelemetry (ImagePath executes telemetry_service.ps1 as LocalSystem). preflight.ps1, refresh_cache.ps1, and the DunderTelemetry service registry key are deliberately user-modifiable for classic hijack-and-wait privesc.',
  category              = 'Privilege Escalation',
  difficulty            = 'intermediate',
  services_exposed      = '[]'::jsonb,
  script_type           = 'vulnerable',
  estimated_runtime_sec = 45,
  script_args           = ''
WHERE slug = 'win-priv-esc';

UPDATE vuln_scripts SET
  name                  = 'User Simulation (USER2 + ADMIN)',
  description           = 'Creates USER2 (standard) and ADMIN (local administrator) accounts, seeds realistic profile content (VPN notes, hostname lists, inventory CSVs, maintenance notes) plus shared C:\LabShare and C:\ProgramData\Ops drops. Pure realism, no vuln injection.',
  category              = 'User Simulation',
  difficulty            = 'beginner',
  services_exposed      = '[]'::jsonb,
  script_type           = 'baseline',
  estimated_runtime_sec = 60,
  script_args           = ''
WHERE slug = 'win-life-artifacts';

UPDATE vuln_scripts SET
  name                  = 'OWASP Apps Setup',
  description           = 'Extracts Java 23 + Node.js, verifies WebGoat / Juice Shop / VulnServer downloads from C:\LabApps\installers, installs Node via MSI, opens firewall on 8080/3000/9999, and persists runtime config to C:\LabApps\state\runtime.json. Requires owasp-download to have run first.',
  category              = 'Web Server',
  difficulty            = 'intermediate',
  services_exposed      = '["8080/WebGoat","3000/JuiceShop","9091/WebWolf","9999/VulnServer"]'::jsonb,
  script_type           = 'baseline',
  estimated_runtime_sec = 600,
  script_args           = '-Setup'
WHERE slug = 'win-owasp-setup';

UPDATE vuln_scripts SET
  name                  = 'MedAlliance T1 (Full Stack)',
  description           = 'Tier-1 MedAlliance lab: IIS (80 corporate landing + 8080 Health Monitor dashboard), IIS FTP (21 anonymous read on /logs), SQL Server Express (SA=SQLAdmin2024!, xp_cmdshell enabled, hr_database with 20 employees + payroll + system_credentials), WinRM (5985), RDP (3389). Branches Server vs. Client SKUs; SQL section auto-skips if no MSSQL service present.',
  category              = 'Composite Lab',
  difficulty            = 'advanced',
  services_exposed      = '["80/HTTP","8080/HealthMonitor","21/FTP","1433/MSSQL","5985/WinRM","3389/RDP","445/SMB"]'::jsonb,
  script_type           = 'vulnerable',
  estimated_runtime_sec = 600,
  script_args           = ''
WHERE slug = 'win-install-480-services';

UPDATE vuln_scripts SET
  name                  = 'DunderCorp Attack Path (Part 1)',
  description           = 'Combined orchestrator for the DunderCorp Part-1 challenge narrative. Stages users, shares, persistence, privesc, and credential artifacts in one run.',
  category              = 'Composite Lab',
  difficulty            = 'advanced',
  services_exposed      = '[]'::jsonb,
  script_type           = 'vulnerable',
  estimated_runtime_sec = 600,
  script_args           = ''
WHERE slug = 'win-dundercorp-full-path-1';

UPDATE vuln_scripts SET
  name                  = 'MedAlliance T1 Artifacts',
  description           = 'Plants per-student unique proof files, breadcrumb docs, and loot content for the MedAlliance Tier-1 challenge. Depends on the shares + users scripts having run first.',
  category              = 'User Simulation',
  difficulty            = 'intermediate',
  services_exposed      = '[]'::jsonb,
  script_type           = 'vulnerable',
  estimated_runtime_sec = 120,
  script_args           = ''
WHERE slug = 'win-480-artifacts';

UPDATE vuln_scripts SET
  name                  = 'MedAlliance T1 Users',
  description           = 'Creates m.chen (standard, RDP + WinRM groups, password MedAlliance2024! matching the Linux loot), MedHealthSvc service account, sets a strong Administrator password only reachable via privesc, drops a cmdkey saved-credential artifact, and writes personal_notes.txt in m.chen''s Documents with passwords jotted down (realistic sticky-note pattern).',
  category              = 'User Simulation',
  difficulty            = 'intermediate',
  services_exposed      = '[]'::jsonb,
  script_type           = 'vulnerable',
  estimated_runtime_sec = 45,
  script_args           = ''
WHERE slug = 'win-480-config-users';

UPDATE vuln_scripts SET
  name                  = 'MedAlliance T1 Shares',
  description           = 'Creates SMB shares populated with realistic corporate documents (financial reports, HR records, IT runbooks) laced with planted credentials, internal hostnames, and sensitive data for the MedAlliance Tier-1 challenge.',
  category              = 'Data Exfiltration',
  difficulty            = 'intermediate',
  services_exposed      = '["445/SMB"]'::jsonb,
  script_type           = 'vulnerable',
  estimated_runtime_sec = 60,
  script_args           = ''
WHERE slug = 'win-480-config-shares';

UPDATE vuln_scripts SET
  name                  = 'SSH (Start Service)',
  description           = 'Enables the sshd service with automatic startup, ensures DefaultShell is PowerShell, and reports port-22 listen status. No vulnerabilities injected.',
  category              = 'Network Services',
  difficulty            = 'beginner',
  services_exposed      = '["22/SSH"]'::jsonb,
  script_type           = 'baseline',
  estimated_runtime_sec = 15,
  script_args           = ''
WHERE slug = 'win-start-ssh';

UPDATE vuln_scripts SET
  name                  = 'OWASP Apps Start',
  description           = 'Starts WebGoat (8080), Juice Shop (3000), and VulnServer (9999) after owasp-setup has provisioned them. Uses launcher scripts under C:\LabApps\state and tails logs for readiness checks.',
  category              = 'Web Server',
  difficulty            = 'intermediate',
  services_exposed      = '["8080/WebGoat","3000/JuiceShop","9091/WebWolf","9999/VulnServer"]'::jsonb,
  script_type           = 'baseline',
  estimated_runtime_sec = 60,
  script_args           = '-Start'
WHERE slug = 'win-owasp-start';

-- ---------- PART 2: new Phase-1 scripts ----------

INSERT INTO vuln_scripts (slug, name, description, category, os_target, difficulty, script_content, services_exposed, depends_on, estimated_runtime_sec, is_active, script_args, script_type) VALUES (
  'init-setup',
  'Lab Bootstrap',
  'Execution policy, firewall basics, lab directory tree (C:\Lab / LabApps / LabShare), ICMP allow, high-perf power plan, student + svcbackup accounts. Foundation for every other script.',
  'Initial Setup',
  'windows',
  'beginner',
  $INIT_SETUP$$ErrorActionPreference = "Continue"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message"
}

# --- Execution policy (so dependent scripts run without prompts) ---
Write-Step "Setting execution policy to Bypass for CurrentUser and LocalMachine"
Set-ExecutionPolicy -Scope LocalMachine -ExecutionPolicy Bypass -Force -ErrorAction SilentlyContinue
Set-ExecutionPolicy -Scope CurrentUser  -ExecutionPolicy Bypass -Force -ErrorAction SilentlyContinue

# --- Lab directory tree used by other scripts ---
Write-Step "Creating C:\Lab working directories"
foreach ($dir in @("C:\Lab","C:\Lab\logs","C:\Lab\artifacts","C:\Lab\tools","C:\Lab\loot","C:\LabApps","C:\LabShare")) {
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
}

# --- Set network profile to Private (lets SMB/WinRM/RDP firewall rules apply) ---
Write-Step "Setting all network profiles to Private"
Get-NetConnectionProfile -ErrorAction SilentlyContinue | ForEach-Object {
    if ($_.NetworkCategory -ne "Private") {
        Set-NetConnectionProfile -InterfaceIndex $_.InterfaceIndex -NetworkCategory Private -ErrorAction SilentlyContinue
    }
}

# --- Allow ICMP echo (ping) so students can enumerate ---
Write-Step "Enabling ICMPv4 echo-request in firewall"
Get-NetFirewallRule -Name "FPS-ICMP4-ERQ-In" -ErrorAction SilentlyContinue | Enable-NetFirewallRule -ErrorAction SilentlyContinue
New-NetFirewallRule -DisplayName "Lab-ICMP-Allow-In" -Direction Inbound -Protocol ICMPv4 -IcmpType 8 -Action Allow -Profile Any -ErrorAction SilentlyContinue | Out-Null

# --- High-performance power plan (keeps VMs responsive for live demos) ---
Write-Step "Switching to High Performance power plan"
try { powercfg -setactive SCHEME_MIN 2>$null } catch {}

# --- Stamp a lab marker so students can find the environment build info ---
Write-Step "Writing C:\Lab\lab-info.txt"
$info = @"
Lab Environment
---------------
Built       : $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
Hostname    : $env:COMPUTERNAME
OS Version  : $((Get-CimInstance Win32_OperatingSystem).Caption)
Arch        : $env:PROCESSOR_ARCHITECTURE
Admin User  : Administrator
Contact     : support@internal.lab
"@
Set-Content "C:\Lab\lab-info.txt" $info -Encoding UTF8

# --- Create a dedicated non-privileged student account used across lab scripts ---
Write-Step "Ensuring student accounts exist"
$pw = ConvertTo-SecureString "LabStudent!" -AsPlainText -Force
$accounts = @(
    @{ Name = "student";  FullName = "Lab Student";     Group = "Users" },
    @{ Name = "svcbackup"; FullName = "Backup Service"; Group = "Backup Operators" }
)
foreach ($acct in $accounts) {
    $existing = Get-LocalUser -Name $acct.Name -ErrorAction SilentlyContinue
    if (-not $existing) {
        New-LocalUser -Name $acct.Name -Password $pw -FullName $acct.FullName -Description "Lab account" -PasswordNeverExpires -UserMayNotChangePassword -ErrorAction SilentlyContinue | Out-Null
        Add-LocalGroupMember -Group $acct.Group -Member $acct.Name -ErrorAction SilentlyContinue
    }
}

Write-Host ""
Write-Host "=== init-setup complete ==="
Write-Host "Lab tree : C:\Lab, C:\LabApps, C:\LabShare"
Write-Host "Accounts : student / svcbackup (password LabStudent!)"
Write-Host "ICMP     : allowed"
$INIT_SETUP$,
  '[]'::jsonb,
  '{}',
  20,
  true,
  '',
  'baseline'
)
ON CONFLICT (slug) DO UPDATE SET
  name                  = EXCLUDED.name,
  description           = EXCLUDED.description,
  category              = EXCLUDED.category,
  difficulty            = EXCLUDED.difficulty,
  script_content        = EXCLUDED.script_content,
  services_exposed      = EXCLUDED.services_exposed,
  depends_on            = EXCLUDED.depends_on,
  estimated_runtime_sec = EXCLUDED.estimated_runtime_sec,
  is_active             = true,
  script_args           = EXCLUDED.script_args,
  script_type           = EXCLUDED.script_type;

INSERT INTO vuln_scripts (slug, name, description, category, os_target, difficulty, script_content, services_exposed, depends_on, estimated_runtime_sec, is_active, script_args, script_type) VALUES (
  'smb-baseline',
  'SMB (Standard-Secure)',
  'Public + Users shares with authenticated-only access, SMB signing required, SMB1 disabled, null sessions blocked. Clean baseline for real-client synthesis.',
  'Network Services',
  'windows',
  'beginner',
  $SMB_BASELINE$$ErrorActionPreference = "Continue"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message"
}

# Baseline SMB: enable file sharing with authenticated-only access.
# NO null session, NO anonymous enumeration, NO guest access.
# Use smb-config.ps1 if you want the vulnerable variant.

$BasePath = "C:\LabShare"

Write-Step "Setting network profile to Private"
Get-NetConnectionProfile -ErrorAction SilentlyContinue | ForEach-Object {
    if ($_.NetworkCategory -ne "Private") {
        Set-NetConnectionProfile -InterfaceIndex $_.InterfaceIndex -NetworkCategory Private -ErrorAction SilentlyContinue
    }
}

Write-Step "Enabling File and Printer Sharing firewall rules"
Enable-NetFirewallRule -DisplayGroup "File and Printer Sharing" -ErrorAction SilentlyContinue | Out-Null

Write-Step "Creating share folders"
foreach ($folder in @($BasePath, "$BasePath\Public", "$BasePath\Users")) {
    if (-not (Test-Path $folder)) { New-Item -ItemType Directory -Path $folder -Force | Out-Null }
}

Write-Step "Setting NTFS permissions (authenticated users only)"
icacls "$BasePath\Public" /inheritance:r /grant:r "Authenticated Users:(OI)(CI)RX" "Administrators:(OI)(CI)F" | Out-Null
icacls "$BasePath\Users"  /inheritance:r /grant:r "Users:(OI)(CI)M"                "Administrators:(OI)(CI)F" | Out-Null

Write-Step "Creating SMB shares"
foreach ($name in @("Public","Users")) {
    $existing = Get-SmbShare -Name $name -ErrorAction SilentlyContinue
    if ($existing) { Remove-SmbShare -Name $name -Force -ErrorAction SilentlyContinue }
}
New-SmbShare -Name "Public" -Path "$BasePath\Public" -ReadAccess  "Authenticated Users" -FullAccess "Administrators" -ErrorAction SilentlyContinue | Out-Null
New-SmbShare -Name "Users"  -Path "$BasePath\Users"  -ChangeAccess "Users"               -FullAccess "Administrators" -ErrorAction SilentlyContinue | Out-Null

Write-Step "Enforcing secure SMB settings (signing required, no null session)"
# Server-side: require signing, deny null sessions
Set-SmbServerConfiguration -RequireSecuritySignature $true -EnableSecuritySignature $true -Confirm:$false -ErrorAction SilentlyContinue
Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters" -Name "RestrictNullSessAccess" -Value 1 -Type DWord -Force
Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa"                      -Name "RestrictAnonymous"     -Value 1 -Type DWord -Force

# Disable SMBv1 entirely (current best practice)
Set-SmbServerConfiguration -EnableSMB1Protocol $false -Confirm:$false -ErrorAction SilentlyContinue

Write-Step "Seeding a small amount of realistic content"
Set-Content "$BasePath\Public\README.txt" @"
Public share. Read-only for authenticated users.
For team files, use the Users share.
"@ -Encoding UTF8

Write-Host ""
Write-Host "=== smb-baseline complete ==="
Write-Host "Shares    : Public (auth read), Users (auth RW)"
Write-Host "SMB1      : disabled"
Write-Host "Signing   : required"
Write-Host "Null sess : blocked"
$SMB_BASELINE$,
  '["445/SMB"]'::jsonb,
  '{"init-setup"}',
  20,
  true,
  '',
  'baseline'
)
ON CONFLICT (slug) DO UPDATE SET
  name                  = EXCLUDED.name,
  description           = EXCLUDED.description,
  category              = EXCLUDED.category,
  difficulty            = EXCLUDED.difficulty,
  script_content        = EXCLUDED.script_content,
  services_exposed      = EXCLUDED.services_exposed,
  depends_on            = EXCLUDED.depends_on,
  estimated_runtime_sec = EXCLUDED.estimated_runtime_sec,
  is_active             = true,
  script_args           = EXCLUDED.script_args,
  script_type           = EXCLUDED.script_type;

INSERT INTO vuln_scripts (slug, name, description, category, os_target, difficulty, script_content, services_exposed, depends_on, estimated_runtime_sec, is_active, script_args, script_type) VALUES (
  'rdp-baseline',
  'RDP (Standard-Secure)',
  'RDP on 3389 with NLA required, TLS security layer, high encryption. Only the student account granted access.',
  'Network Services',
  'windows',
  'beginner',
  $RDP_BASELINE$$ErrorActionPreference = "Continue"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message"
}

# Baseline RDP: enable with NLA + TLS, grant specific users only.
# Use rdp-config.ps1 for the NLA-off / low-security-layer variant.

Write-Step "Enabling Remote Desktop"
Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0 -Force

Write-Step "Requiring Network Level Authentication"
Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 1 -Force
# SecurityLayer = 2 means SSL (TLS 1.0) required
Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "SecurityLayer"     -Value 2 -Force
# MinEncryptionLevel = 3 means High encryption required (128-bit)
Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "MinEncryptionLevel" -Value 3 -Force

Write-Step "Enabling Remote Desktop firewall group"
Enable-NetFirewallRule -DisplayGroup "Remote Desktop" -ErrorAction SilentlyContinue | Out-Null

Write-Step "Granting RDP access to student (only)"
try { Add-LocalGroupMember -Group "Remote Desktop Users" -Member "student" -ErrorAction SilentlyContinue } catch {}

Write-Step "Starting Remote Desktop Services"
Set-Service -Name TermService -StartupType Automatic -ErrorAction SilentlyContinue
Start-Service -Name TermService -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "=== rdp-baseline complete ==="
Write-Host "Port 3389     : open"
Write-Host "NLA           : required"
Write-Host "Security      : TLS + high encryption"
Write-Host "RDP users     : student"
$RDP_BASELINE$,
  '["3389/RDP"]'::jsonb,
  '{"init-setup"}',
  10,
  true,
  '',
  'baseline'
)
ON CONFLICT (slug) DO UPDATE SET
  name                  = EXCLUDED.name,
  description           = EXCLUDED.description,
  category              = EXCLUDED.category,
  difficulty            = EXCLUDED.difficulty,
  script_content        = EXCLUDED.script_content,
  services_exposed      = EXCLUDED.services_exposed,
  depends_on            = EXCLUDED.depends_on,
  estimated_runtime_sec = EXCLUDED.estimated_runtime_sec,
  is_active             = true,
  script_args           = EXCLUDED.script_args,
  script_type           = EXCLUDED.script_type;

INSERT INTO vuln_scripts (slug, name, description, category, os_target, difficulty, script_content, services_exposed, depends_on, estimated_runtime_sec, is_active, script_args, script_type) VALUES (
  'ssh-baseline',
  'OpenSSH (Standard)',
  'Installs OpenSSH Server Windows capability, starts sshd + ssh-agent with stock config, opens port 22. No seeded keys or relaxed auth.',
  'Network Services',
  'windows',
  'beginner',
  $SSH_BASELINE$$ErrorActionPreference = "Continue"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message"
}

# Baseline OpenSSH: install + start sshd with stock sshd_config.
# No seeded keys, no relaxed auth. Use ssh-config.ps1 for the artifact-rich variant.

Write-Step "Installing OpenSSH Server Windows capability"
try {
    $cap = Get-WindowsCapability -Online -Name "OpenSSH.Server*" -ErrorAction SilentlyContinue
    if ($cap -and $cap.State -ne 'Installed') {
        Add-WindowsCapability -Online -Name $cap.Name -ErrorAction SilentlyContinue | Out-Null
    }
} catch { Write-Host "OpenSSH capability install: $($_.Exception.Message)" }

Write-Step "Starting sshd service"
Set-Service -Name sshd -StartupType Automatic -ErrorAction SilentlyContinue
Start-Service -Name sshd -ErrorAction SilentlyContinue

# Also start the agent so pubkey workflows work if admin uses them later
Set-Service -Name 'ssh-agent' -StartupType Automatic -ErrorAction SilentlyContinue
Start-Service -Name 'ssh-agent' -ErrorAction SilentlyContinue

Write-Step "Opening TCP/22 in firewall"
Get-NetFirewallRule -Name "OpenSSH-Server-In-TCP" -ErrorAction SilentlyContinue | Enable-NetFirewallRule -ErrorAction SilentlyContinue
New-NetFirewallRule -DisplayName "Lab-SSH-22-Allow" -Direction Inbound -Protocol TCP -LocalPort 22 -Action Allow -Profile Any -ErrorAction SilentlyContinue | Out-Null

# Use the shipped sshd_config defaults -- no permissive overrides here.
# (The OpenSSH-Server capability installs a sane default config.)

Write-Step "Ensuring default shell is PowerShell for SSH sessions"
try {
    $regPath = "HKLM:\SOFTWARE\OpenSSH"
    if (-not (Test-Path $regPath)) { New-Item -Path $regPath -Force | Out-Null }
    New-ItemProperty -Path $regPath -Name DefaultShell -PropertyType String -Value (Get-Command powershell.exe).Source -Force | Out-Null
} catch {}

Write-Host ""
Write-Host "=== ssh-baseline complete ==="
Write-Host "Service   : sshd + ssh-agent started (auto)"
Write-Host "Port      : 22/TCP"
Write-Host "Config    : stock (no relaxed auth)"
$SSH_BASELINE$,
  '["22/SSH"]'::jsonb,
  '{"init-setup"}',
  90,
  true,
  '',
  'baseline'
)
ON CONFLICT (slug) DO UPDATE SET
  name                  = EXCLUDED.name,
  description           = EXCLUDED.description,
  category              = EXCLUDED.category,
  difficulty            = EXCLUDED.difficulty,
  script_content        = EXCLUDED.script_content,
  services_exposed      = EXCLUDED.services_exposed,
  depends_on            = EXCLUDED.depends_on,
  estimated_runtime_sec = EXCLUDED.estimated_runtime_sec,
  is_active             = true,
  script_args           = EXCLUDED.script_args,
  script_type           = EXCLUDED.script_type;

INSERT INTO vuln_scripts (slug, name, description, category, os_target, difficulty, script_content, services_exposed, depends_on, estimated_runtime_sec, is_active, script_args, script_type) VALUES (
  'winrm-baseline',
  'WinRM HTTPS (Hardened)',
  'HTTPS listener on 5986 with self-signed cert, Kerberos + Negotiate auth only, Basic auth denied, unencrypted transport denied. Removes the default HTTP listener.',
  'Network Services',
  'windows',
  'intermediate',
  $WINRM_BASELINE$$ErrorActionPreference = "Continue"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message"
}

# Baseline WinRM: HTTPS listener with self-signed cert, Kerberos/Negotiate only,
# no Basic auth, no unencrypted. Use winrm-http.ps1 for the unencrypted variant.

Write-Step "Starting WinRM service"
Set-Service -Name WinRM -StartupType Automatic -ErrorAction SilentlyContinue
Start-Service -Name WinRM -ErrorAction SilentlyContinue

Write-Step "Bootstrapping PSRemoting (SkipNetworkProfileCheck)"
Enable-PSRemoting -Force -SkipNetworkProfileCheck -ErrorAction SilentlyContinue | Out-Null

Write-Step "Creating self-signed certificate for HTTPS listener"
$cert = Get-ChildItem Cert:\LocalMachine\My | Where-Object { $_.Subject -eq "CN=$env:COMPUTERNAME" -and $_.EnhancedKeyUsageList.ObjectId -contains '1.3.6.1.5.5.7.3.1' } | Select-Object -First 1
if (-not $cert) {
    $cert = New-SelfSignedCertificate -DnsName $env:COMPUTERNAME -CertStoreLocation Cert:\LocalMachine\My -KeyExportPolicy Exportable -Provider "Microsoft Enhanced RSA and AES Cryptographic Provider" -ErrorAction SilentlyContinue
}

Write-Step "Configuring HTTPS listener on 5986"
if ($cert) {
    # Remove existing HTTPS listeners to avoid conflicts, then recreate
    & winrm delete winrm/config/Listener?Address=*+Transport=HTTPS 2>$null | Out-Null
    & winrm create winrm/config/Listener?Address=*+Transport=HTTPS "@{Hostname=`"$env:COMPUTERNAME`";CertificateThumbprint=`"$($cert.Thumbprint)`"}" 2>$null | Out-Null
}

# Delete the default HTTP listener created by Enable-PSRemoting
& winrm delete winrm/config/Listener?Address=*+Transport=HTTP 2>$null | Out-Null

Write-Step "Hardening auth: Kerberos/Negotiate only, no Basic, no unencrypted"
& winrm set winrm/config/service           '@{AllowUnencrypted="false"}' 2>$null | Out-Null
& winrm set winrm/config/service/auth      '@{Basic="false";Kerberos="true";Negotiate="true";CredSSP="false"}' 2>$null | Out-Null
& winrm set winrm/config/client            '@{AllowUnencrypted="false"}' 2>$null | Out-Null
& winrm set winrm/config/client/auth       '@{Basic="false";Kerberos="true";Negotiate="true"}' 2>$null | Out-Null

Write-Step "Opening TCP/5986 (HTTPS) in firewall; removing 5985 if present"
New-NetFirewallRule -DisplayName "Lab-WinRM-5986-Allow" -Direction Inbound -Protocol TCP -LocalPort 5986 -Action Allow -Profile Any -ErrorAction SilentlyContinue | Out-Null
Get-NetFirewallRule -DisplayName "Lab-WinRM-5985-Allow" -ErrorAction SilentlyContinue | Remove-NetFirewallRule -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "=== winrm-baseline complete ==="
Write-Host "HTTPS listener : 5986/TCP (self-signed cert)"
Write-Host "HTTP listener  : removed"
Write-Host "Auth           : Kerberos + Negotiate (no Basic)"
Write-Host "Unencrypted    : denied"
$WINRM_BASELINE$,
  '["5986/WinRM-HTTPS"]'::jsonb,
  '{"init-setup"}',
  30,
  true,
  '',
  'baseline'
)
ON CONFLICT (slug) DO UPDATE SET
  name                  = EXCLUDED.name,
  description           = EXCLUDED.description,
  category              = EXCLUDED.category,
  difficulty            = EXCLUDED.difficulty,
  script_content        = EXCLUDED.script_content,
  services_exposed      = EXCLUDED.services_exposed,
  depends_on            = EXCLUDED.depends_on,
  estimated_runtime_sec = EXCLUDED.estimated_runtime_sec,
  is_active             = true,
  script_args           = EXCLUDED.script_args,
  script_type           = EXCLUDED.script_type;

INSERT INTO vuln_scripts (slug, name, description, category, os_target, difficulty, script_content, services_exposed, depends_on, estimated_runtime_sec, is_active, script_args, script_type) VALUES (
  'http-baseline',
  'IIS HTTP (Standard)',
  'Installs IIS, serves a plain corporate landing page on port 80. No vulnerable apps, no FTP, no anonymous. Clean baseline for real-client synthesis.',
  'Network Services',
  'windows',
  'beginner',
  $HTTP_BASELINE$$ErrorActionPreference = "Continue"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message"
}

# Baseline HTTP: install IIS, serve a plain corporate landing page on port 80.
# No vulnerable apps (WebGoat / Juice Shop / VulnServer), no FTP, no anonymous
# shares. Counterpart to iis-config (vulnerable) and win-install-480-services
# (composite vulnerable lab).

Write-Step "Installing IIS web server role"
$isServer = (Get-CimInstance Win32_OperatingSystem).ProductType -ne 1
if ($isServer) {
    Install-WindowsFeature -Name Web-Server,Web-Common-Http,Web-Default-Doc,Web-Static-Content,Web-Http-Logging,Web-Filtering -IncludeManagementTools -ErrorAction SilentlyContinue | Out-Null
} else {
    Enable-WindowsOptionalFeature -Online -FeatureName IIS-WebServerRole,IIS-WebServer,IIS-CommonHttpFeatures,IIS-DefaultDocument,IIS-StaticContent,IIS-HttpLogging -NoRestart -All -ErrorAction SilentlyContinue | Out-Null
}

Write-Step "Creating placeholder corporate landing page"
$wwwroot = "C:\inetpub\wwwroot"
if (-not (Test-Path $wwwroot)) { New-Item -Path $wwwroot -ItemType Directory -Force | Out-Null }

# Clear the stock IIS welcome page
Remove-Item "$wwwroot\iisstart.htm" -Force -ErrorAction SilentlyContinue
Remove-Item "$wwwroot\iisstart.png" -Force -ErrorAction SilentlyContinue

$landingPage = @"
<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Internal Portal</title>
<style>
body { font-family: 'Segoe UI', system-ui, sans-serif; background: #f0f2f5; color: #333; margin: 0; }
.nav { background: #0a2540; color: #fff; padding: 16px 32px; }
.nav h1 { font-size: 18px; font-weight: 600; margin: 0; }
.wrap { max-width: 780px; margin: 40px auto; padding: 0 20px; }
.card { background: #fff; border-radius: 12px; padding: 28px; margin-bottom: 20px;
        box-shadow: 0 1px 3px rgba(0,0,0,.08); border: 1px solid #e8e8e8; }
.card h2 { font-size: 15px; color: #0a2540; margin: 0 0 12px; padding-bottom: 10px; border-bottom: 1px solid #eee; }
.card p { line-height: 1.65; color: #555; margin: 0 0 10px; font-size: 14px; }
.footer { text-align: center; color: #aaa; font-size: 12px; padding: 30px 0; }
</style>
</head><body>
<div class="nav"><h1>Internal Portal</h1></div>
<div class="wrap">
  <div class="card">
    <h2>Staff Resources</h2>
    <p>For access to internal systems, contact IT at ext. 4200 or support@internal.lab.</p>
    <p>Password resets, software requests, and hardware issues should be submitted via the ticketing portal.</p>
  </div>
  <div class="card">
    <h2>Service Status</h2>
    <p>All services are operating normally. Scheduled maintenance windows are posted in the IT calendar.</p>
  </div>
</div>
<div class="footer">Internal IT Portal &copy; 2024 | IIS/10.0</div>
</body></html>
"@
Set-Content -Path "$wwwroot\index.html" -Value $landingPage -Encoding UTF8

Write-Step "Opening TCP/80 in firewall"
Enable-NetFirewallRule -DisplayGroup "World Wide Web Services (HTTP)" -ErrorAction SilentlyContinue | Out-Null
New-NetFirewallRule -DisplayName "Lab-HTTP-80-Allow" -Direction Inbound -Protocol TCP -LocalPort 80 -Action Allow -Profile Any -ErrorAction SilentlyContinue | Out-Null

Write-Step "Starting W3SVC"
Set-Service -Name W3SVC -StartupType Automatic -ErrorAction SilentlyContinue
Start-Service -Name W3SVC -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "=== http-baseline complete ==="
Write-Host "Site     : http://$env:COMPUTERNAME/"
Write-Host "Port     : 80/TCP"
Write-Host "Content  : corporate landing page (no vulnerable apps)"
$HTTP_BASELINE$,
  '["80/HTTP"]'::jsonb,
  '{"init-setup"}',
  120,
  true,
  '',
  'baseline'
)
ON CONFLICT (slug) DO UPDATE SET
  name                  = EXCLUDED.name,
  description           = EXCLUDED.description,
  category              = EXCLUDED.category,
  difficulty            = EXCLUDED.difficulty,
  script_content        = EXCLUDED.script_content,
  services_exposed      = EXCLUDED.services_exposed,
  depends_on            = EXCLUDED.depends_on,
  estimated_runtime_sec = EXCLUDED.estimated_runtime_sec,
  is_active             = true,
  script_args           = EXCLUDED.script_args,
  script_type           = EXCLUDED.script_type;

INSERT INTO vuln_scripts (slug, name, description, category, os_target, difficulty, script_content, services_exposed, depends_on, estimated_runtime_sec, is_active, script_args, script_type) VALUES (
  'mssql-baseline',
  'MSSQL (Hardened)',
  'Configures an already-installed SQL Server instance for Windows-auth only, disables SA, disables xp_cmdshell, enables TCP on 1433, opens firewall. No-ops if no MSSQL service is present.',
  'Network Services',
  'windows',
  'intermediate',
  $MSSQL_BASELINE$$ErrorActionPreference = "Continue"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message"
}

# Baseline MSSQL: if SQL Express is already installed, configure it safely --
# Windows-auth only, xp_cmdshell disabled, SA disabled, TCP on 1433 with
# standard firewall rule. Does NOT install SQL Server (that's a heavy download
# and belongs in a Proxmox template or separate install script).

$sqlService = Get-Service -Name 'MSSQL*' -ErrorAction SilentlyContinue |
              Where-Object { $_.Name -like 'MSSQL$*' -or $_.Name -eq 'MSSQLSERVER' } |
              Select-Object -First 1

if (-not $sqlService) {
    Write-Host "No MSSQL service detected on this host -- skipping SQL baseline."
    Write-Host "Install SQL Server Express first, then re-run this script."
    [Environment]::Exit(0)
}

Write-Step "Found SQL service: $($sqlService.Name)"
Set-Service -Name $sqlService.Name -StartupType Automatic -ErrorAction SilentlyContinue
Start-Service -Name $sqlService.Name -ErrorAction SilentlyContinue

# Instance short name for sqlcmd -S argument
$instanceName = if ($sqlService.Name -like 'MSSQL$*') { $sqlService.Name.Substring(6) } else { 'MSSQLSERVER' }
$sqlServerArg = if ($instanceName -eq 'MSSQLSERVER') { '.' } else { ".\$instanceName" }

Write-Step "Forcing Windows-authentication-only (LoginMode=1)"
$regBase = "HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server"
$instances = Get-ChildItem $regBase -ErrorAction SilentlyContinue |
             Where-Object { $_.Name -match "MSSQL\d+\.$instanceName" }
foreach ($inst in $instances) {
    $serverPath = "$($inst.PSPath)\MSSQLServer"
    if (Test-Path $serverPath) {
        Set-ItemProperty -Path $serverPath -Name "LoginMode" -Value 1 -Force
    }
}

Write-Step "Enabling TCP/IP on port 1433 (standard)"
foreach ($inst in $instances) {
    $tcpPath = "$($inst.PSPath)\MSSQLServer\SuperSocketNetLib\Tcp"
    if (Test-Path $tcpPath) {
        Set-ItemProperty -Path $tcpPath -Name "Enabled" -Value 1 -Force
        $ipAllPath = "$tcpPath\IPAll"
        if (Test-Path $ipAllPath) {
            Set-ItemProperty -Path $ipAllPath -Name "TcpPort" -Value "1433" -Force
            Set-ItemProperty -Path $ipAllPath -Name "TcpDynamicPorts" -Value "" -Force
        }
    }
}

Restart-Service -Name $sqlService.Name -Force -ErrorAction SilentlyContinue
Start-Sleep -Seconds 8

# Find sqlcmd
$sqlcmd = $null
foreach ($pattern in @(
    "C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\*\Tools\Binn\SQLCMD.EXE",
    "C:\Program Files\Microsoft SQL Server\*\Tools\Binn\SQLCMD.EXE"
)) {
    $found = Get-ChildItem -Path $pattern -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($found) { $sqlcmd = $found.FullName; break }
}

if ($sqlcmd) {
    Write-Step "Disabling SA + xp_cmdshell"
    & $sqlcmd -S $sqlServerArg -E -Q "ALTER LOGIN [sa] DISABLE;" 2>&1 | Out-Null
    & $sqlcmd -S $sqlServerArg -E -Q @"
EXEC sp_configure 'show advanced options', 1; RECONFIGURE;
EXEC sp_configure 'xp_cmdshell', 0; RECONFIGURE;
EXEC sp_configure 'show advanced options', 0; RECONFIGURE;
"@ 2>&1 | Out-Null
} else {
    Write-Host "sqlcmd not found -- SA disable + xp_cmdshell lockdown skipped."
}

Write-Step "Opening TCP/1433 in firewall"
New-NetFirewallRule -DisplayName "Lab-MSSQL-1433-Allow" -Direction Inbound -Protocol TCP -LocalPort 1433 -Action Allow -Profile Any -ErrorAction SilentlyContinue | Out-Null

Write-Host ""
Write-Host "=== mssql-baseline complete ==="
Write-Host "Auth mode     : Windows-only"
Write-Host "SA account    : disabled"
Write-Host "xp_cmdshell   : disabled"
Write-Host "Port          : 1433/TCP"
$MSSQL_BASELINE$,
  '["1433/SQL"]'::jsonb,
  '{"init-setup"}',
  60,
  true,
  '',
  'baseline'
)
ON CONFLICT (slug) DO UPDATE SET
  name                  = EXCLUDED.name,
  description           = EXCLUDED.description,
  category              = EXCLUDED.category,
  difficulty            = EXCLUDED.difficulty,
  script_content        = EXCLUDED.script_content,
  services_exposed      = EXCLUDED.services_exposed,
  depends_on            = EXCLUDED.depends_on,
  estimated_runtime_sec = EXCLUDED.estimated_runtime_sec,
  is_active             = true,
  script_args           = EXCLUDED.script_args,
  script_type           = EXCLUDED.script_type;

INSERT INTO vuln_scripts (slug, name, description, category, os_target, difficulty, script_content, services_exposed, depends_on, estimated_runtime_sec, is_active, script_args, script_type) VALUES (
  'ftp-baseline',
  'IIS FTP (Authenticated, SSL)',
  'IIS FTP on port 21 with anonymous disabled, basic auth required, SSL enforced on control + data channels using a self-signed cert. Counterpart to ftp-anonymous.',
  'Network Services',
  'windows',
  'intermediate',
  $FTP_BASELINE$$ErrorActionPreference = "Continue"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message"
}

# Baseline FTP: IIS FTP on port 21 with authentication required (NO anonymous),
# SSL policy set to require SSL for both control + data channels. Counterpart
# to ftp-anonymous (vulnerable).

Write-Step "Installing IIS + FTP features"
$isServer = (Get-CimInstance Win32_OperatingSystem).ProductType -ne 1
if ($isServer) {
    Install-WindowsFeature -Name Web-Server,Web-Ftp-Server,Web-Ftp-Service -IncludeManagementTools -ErrorAction SilentlyContinue | Out-Null
} else {
    Enable-WindowsOptionalFeature -Online -FeatureName IIS-WebServerRole,IIS-FTPServer,IIS-FTPSvc -All -NoRestart -ErrorAction SilentlyContinue | Out-Null
}

$ftpRoot = "C:\FTP\Shared"
Write-Step "Creating FTP root at $ftpRoot"
if (-not (Test-Path $ftpRoot)) { New-Item -Path $ftpRoot -ItemType Directory -Force | Out-Null }

Set-Content "$ftpRoot\README.txt" @"
Authenticated FTP share.
Contact IT for credentials. Anonymous access is not permitted.
"@ -Encoding ASCII

# Self-signed cert for FTPS
Write-Step "Creating self-signed cert for FTPS"
$cert = Get-ChildItem Cert:\LocalMachine\My |
        Where-Object { $_.Subject -eq "CN=$env:COMPUTERNAME-ftp" } |
        Select-Object -First 1
if (-not $cert) {
    $cert = New-SelfSignedCertificate -DnsName "$env:COMPUTERNAME-ftp" -CertStoreLocation Cert:\LocalMachine\My -KeyExportPolicy Exportable -ErrorAction SilentlyContinue
}

Import-Module WebAdministration -ErrorAction SilentlyContinue

$siteName = "LabFTP"
Write-Step "Configuring FTP site '$siteName' on port 21 (authenticated, SSL required)"
try {
    if (Get-WebSite -Name $siteName -ErrorAction SilentlyContinue) { Remove-WebSite -Name $siteName -ErrorAction SilentlyContinue }
    New-WebFtpSite -Name $siteName -Port 21 -PhysicalPath $ftpRoot -Force -ErrorAction SilentlyContinue | Out-Null

    # Authenticated only -- anonymous DISABLED
    Set-ItemProperty "IIS:\Sites\$siteName" -Name ftpServer.security.authentication.anonymousAuthentication.enabled -Value $false
    Set-ItemProperty "IIS:\Sites\$siteName" -Name ftpServer.security.authentication.basicAuthentication.enabled     -Value $true

    # Require SSL for both channels (policy=1 == SslRequire)
    Set-ItemProperty "IIS:\Sites\$siteName" -Name ftpServer.security.ssl.controlChannelPolicy -Value 1
    Set-ItemProperty "IIS:\Sites\$siteName" -Name ftpServer.security.ssl.dataChannelPolicy    -Value 1
    if ($cert) {
        Set-ItemProperty "IIS:\Sites\$siteName" -Name ftpServer.security.ssl.serverCertHash -Value $cert.Thumbprint
    }

    # Authorize domain users / local Users group for read; admins full
    Add-WebConfiguration "/system.ftpServer/security/authorization" -Value @{accessType="Allow";roles="Users";permissions=1} -PSPath IIS: -Location $siteName -ErrorAction SilentlyContinue
    Add-WebConfiguration "/system.ftpServer/security/authorization" -Value @{accessType="Allow";roles="Administrators";permissions=3} -PSPath IIS: -Location $siteName -ErrorAction SilentlyContinue
} catch {
    Write-Host "IIS FTP configuration failed: $($_.Exception.Message)"
}

Write-Step "Opening TCP/21 + passive range 40000-40100"
New-NetFirewallRule -DisplayName "Lab-FTP-21-Allow"      -Direction Inbound -Protocol TCP -LocalPort 21          -Action Allow -Profile Any -ErrorAction SilentlyContinue | Out-Null
New-NetFirewallRule -DisplayName "Lab-FTP-Passive-Allow" -Direction Inbound -Protocol TCP -LocalPort 40000-40100 -Action Allow -Profile Any -ErrorAction SilentlyContinue | Out-Null

Start-Service "FTPSVC" -ErrorAction SilentlyContinue
Set-Service   "FTPSVC" -StartupType Automatic -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "=== ftp-baseline complete ==="
Write-Host "Anonymous  : disabled"
Write-Host "Basic auth : required"
Write-Host "SSL        : required (self-signed cert)"
Write-Host "Port       : 21/TCP"
$FTP_BASELINE$,
  '["21/FTP"]'::jsonb,
  '{"init-setup"}',
  180,
  true,
  '',
  'baseline'
)
ON CONFLICT (slug) DO UPDATE SET
  name                  = EXCLUDED.name,
  description           = EXCLUDED.description,
  category              = EXCLUDED.category,
  difficulty            = EXCLUDED.difficulty,
  script_content        = EXCLUDED.script_content,
  services_exposed      = EXCLUDED.services_exposed,
  depends_on            = EXCLUDED.depends_on,
  estimated_runtime_sec = EXCLUDED.estimated_runtime_sec,
  is_active             = true,
  script_args           = EXCLUDED.script_args,
  script_type           = EXCLUDED.script_type;

INSERT INTO vuln_scripts (slug, name, description, category, os_target, difficulty, script_content, services_exposed, depends_on, estimated_runtime_sec, is_active, script_args, script_type) VALUES (
  'dns-baseline',
  'DNS Server (Forwarder)',
  'Windows Server-only: installs the DNS Server role, configures 1.1.1.1 + 8.8.8.8 forwarders with root hints, opens TCP+UDP 53. No-ops on client SKUs.',
  'Network Services',
  'windows',
  'beginner',
  $DNS_BASELINE$$ErrorActionPreference = "Continue"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message"
}

# Baseline DNS: install DNS Server role, configure it to forward upstream,
# open TCP+UDP 53. Intended for a standalone Windows Server (DCs already
# bundle DNS via Install-ADDSForest; this baseline is for a plain DNS host).
# Works on Windows Server only -- DNS Server role is not available on client SKUs.

$isServer = (Get-CimInstance Win32_OperatingSystem).ProductType -ne 1
if (-not $isServer) {
    Write-Host "DNS Server role is Server-only -- this VM is a client SKU. Skipping."
    Write-Host "If you need DNS on a client, use a forwarder (hosts file / Unbound) instead."
    [Environment]::Exit(0)
}

Write-Step "Installing DNS Server role"
Install-WindowsFeature -Name DNS -IncludeManagementTools -ErrorAction SilentlyContinue | Out-Null

Write-Step "Configuring upstream forwarders (1.1.1.1, 8.8.8.8)"
try {
    Set-DnsServerForwarder -IPAddress "1.1.1.1","8.8.8.8" -UseRootHint $true -ErrorAction SilentlyContinue
} catch { Write-Host "Forwarder config failed: $($_.Exception.Message)" }

Write-Step "Opening TCP+UDP 53 in firewall"
New-NetFirewallRule -DisplayName "Lab-DNS-53-TCP-Allow" -Direction Inbound -Protocol TCP -LocalPort 53 -Action Allow -Profile Any -ErrorAction SilentlyContinue | Out-Null
New-NetFirewallRule -DisplayName "Lab-DNS-53-UDP-Allow" -Direction Inbound -Protocol UDP -LocalPort 53 -Action Allow -Profile Any -ErrorAction SilentlyContinue | Out-Null

Set-Service -Name DNS -StartupType Automatic -ErrorAction SilentlyContinue
Start-Service -Name DNS -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "=== dns-baseline complete ==="
Write-Host "Role       : DNS Server"
Write-Host "Forwarders : 1.1.1.1, 8.8.8.8 (+ root hints)"
Write-Host "Ports      : 53/TCP + 53/UDP"
$DNS_BASELINE$,
  '["53/DNS"]'::jsonb,
  '{"init-setup"}',
  60,
  true,
  '',
  'baseline'
)
ON CONFLICT (slug) DO UPDATE SET
  name                  = EXCLUDED.name,
  description           = EXCLUDED.description,
  category              = EXCLUDED.category,
  difficulty            = EXCLUDED.difficulty,
  script_content        = EXCLUDED.script_content,
  services_exposed      = EXCLUDED.services_exposed,
  depends_on            = EXCLUDED.depends_on,
  estimated_runtime_sec = EXCLUDED.estimated_runtime_sec,
  is_active             = true,
  script_args           = EXCLUDED.script_args,
  script_type           = EXCLUDED.script_type;

INSERT INTO vuln_scripts (slug, name, description, category, os_target, difficulty, script_content, services_exposed, depends_on, estimated_runtime_sec, is_active, script_args, script_type) VALUES (
  'rdp-config',
  'RDP (NLA Off)',
  'Enables RDP on 3389, disables NLA, drops to RDP security layer with low encryption, grants student + svcbackup access. Classic brute-force / PtH target.',
  'Network Services',
  'windows',
  'beginner',
  $RDP_CONFIG$$ErrorActionPreference = "Continue"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message"
}

# --- Enable RDP at the registry level ---
Write-Step "Enabling Remote Desktop (fDenyTSConnections = 0)"
Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0 -Force
# Disable Network Level Authentication so older clients (and brute-force tools) can connect
Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 0 -Force
# Keep RDP security layer low (RDP classic, not TLS-enforced)
Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "SecurityLayer" -Value 1 -Force
# Don't force strong encryption
Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "MinEncryptionLevel" -Value 1 -Force

# --- Firewall rule ---
Write-Step "Enabling Remote Desktop firewall group"
Enable-NetFirewallRule -DisplayGroup "Remote Desktop" -ErrorAction SilentlyContinue | Out-Null
New-NetFirewallRule -DisplayName "Lab-RDP-3389-Allow" -Direction Inbound -Protocol TCP -LocalPort 3389 -Action Allow -Profile Any -ErrorAction SilentlyContinue | Out-Null

# --- Allow the student + svcbackup accounts to RDP in ---
Write-Step "Granting RDP access to student + svcbackup"
foreach ($u in @("student","svcbackup")) {
    try { Add-LocalGroupMember -Group "Remote Desktop Users" -Member $u -ErrorAction SilentlyContinue } catch {}
}

# --- Weaken: allow password caching client-side (removes the warning dialog) ---
Write-Step "Disabling 'Always prompt for password' on RDP"
Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "fPromptForPassword" -Value 0 -Force

# --- Ensure TermService is running and set to automatic ---
Write-Step "Starting Remote Desktop Services"
Set-Service -Name TermService -StartupType Automatic -ErrorAction SilentlyContinue
Start-Service -Name TermService -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "=== rdp-config complete ==="
Write-Host "Port 3389 : open"
Write-Host "NLA       : disabled (deliberate lab weakness)"
Write-Host "RDP users : student, svcbackup"
$RDP_CONFIG$,
  '["3389/RDP"]'::jsonb,
  '{"init-setup"}',
  15,
  true,
  '',
  'vulnerable'
)
ON CONFLICT (slug) DO UPDATE SET
  name                  = EXCLUDED.name,
  description           = EXCLUDED.description,
  category              = EXCLUDED.category,
  difficulty            = EXCLUDED.difficulty,
  script_content        = EXCLUDED.script_content,
  services_exposed      = EXCLUDED.services_exposed,
  depends_on            = EXCLUDED.depends_on,
  estimated_runtime_sec = EXCLUDED.estimated_runtime_sec,
  is_active             = true,
  script_args           = EXCLUDED.script_args,
  script_type           = EXCLUDED.script_type;

INSERT INTO vuln_scripts (slug, name, description, category, os_target, difficulty, script_content, services_exposed, depends_on, estimated_runtime_sec, is_active, script_args, script_type) VALUES (
  'winrm-http',
  'WinRM HTTP (Unencrypted + Basic)',
  'Bootstraps PSRemoting with an unencrypted 5985 listener, enables Basic auth + TrustedHosts=*. Exposes WinRM to trivial credential-based RCE.',
  'Network Services',
  'windows',
  'intermediate',
  $WINRM_HTTP$$ErrorActionPreference = "Continue"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message"
}

# --- Enable WinRM service + create HTTP listener ---
Write-Step "Bootstrapping WinRM (Enable-PSRemoting -SkipNetworkProfileCheck)"
Enable-PSRemoting -Force -SkipNetworkProfileCheck -ErrorAction SilentlyContinue | Out-Null

Write-Step "Ensuring HTTP listener exists on 5985"
$listeners = & winrm enumerate winrm/config/Listener 2>$null
if ($LASTEXITCODE -ne 0 -or -not ($listeners -match "Transport = HTTP")) {
    & winrm create winrm/config/Listener?Address=*+Transport=HTTP 2>$null | Out-Null
}

# --- Weaken: allow unencrypted + basic auth (makes CrackMapExec-style auth trivially demonstrable) ---
Write-Step "Enabling unencrypted transport + basic auth (lab weakness)"
& winrm set winrm/config/service '@{AllowUnencrypted="true"}' 2>$null | Out-Null
& winrm set winrm/config/service/auth '@{Basic="true"}'        2>$null | Out-Null
& winrm set winrm/config/client/auth  '@{Basic="true"}'        2>$null | Out-Null
& winrm set winrm/config/client '@{AllowUnencrypted="true"}'   2>$null | Out-Null
& winrm set winrm/config/client '@{TrustedHosts="*"}'          2>$null | Out-Null

# --- Firewall rules ---
Write-Step "Opening 5985/TCP (WinRM HTTP) in firewall"
New-NetFirewallRule -DisplayName "Lab-WinRM-5985-Allow" -Direction Inbound -Protocol TCP -LocalPort 5985 -Action Allow -Profile Any -ErrorAction SilentlyContinue | Out-Null

# --- Make sure WinRM service is automatic + started ---
Set-Service -Name WinRM -StartupType Automatic -ErrorAction SilentlyContinue
Start-Service -Name WinRM -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "=== winrm-http complete ==="
Write-Host "HTTP listener : 5985/TCP"
Write-Host "Basic auth    : ON"
Write-Host "Unencrypted   : ON"
Write-Host "TrustedHosts  : *"
$WINRM_HTTP$,
  '["5985/WinRM"]'::jsonb,
  '{"init-setup"}',
  20,
  true,
  '',
  'vulnerable'
)
ON CONFLICT (slug) DO UPDATE SET
  name                  = EXCLUDED.name,
  description           = EXCLUDED.description,
  category              = EXCLUDED.category,
  difficulty            = EXCLUDED.difficulty,
  script_content        = EXCLUDED.script_content,
  services_exposed      = EXCLUDED.services_exposed,
  depends_on            = EXCLUDED.depends_on,
  estimated_runtime_sec = EXCLUDED.estimated_runtime_sec,
  is_active             = true,
  script_args           = EXCLUDED.script_args,
  script_type           = EXCLUDED.script_type;

INSERT INTO vuln_scripts (slug, name, description, category, os_target, difficulty, script_content, services_exposed, depends_on, estimated_runtime_sec, is_active, script_args, script_type) VALUES (
  'ftp-anonymous',
  'IIS FTP (Anonymous R/W)',
  'Installs IIS FTP role, configures a public site on 21 with anonymous read + write, SSL disabled, seeds plaintext credential files under the FTP root.',
  'Network Services',
  'windows',
  'intermediate',
  $FTP_ANONYMOUS$$ErrorActionPreference = "Continue"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message"
}

# --- Install IIS + FTP role features ---
Write-Step "Installing IIS FTP server features"
$isServer = (Get-CimInstance Win32_OperatingSystem).ProductType -ne 1  # 1 = workstation
if ($isServer) {
    Install-WindowsFeature -Name Web-Server,Web-Ftp-Server,Web-Ftp-Service -IncludeManagementTools -ErrorAction SilentlyContinue | Out-Null
} else {
    # Client-class OS (Win10/11): use DISM
    Enable-WindowsOptionalFeature -Online -FeatureName IIS-WebServerRole,IIS-FTPServer,IIS-FTPSvc -All -NoRestart -ErrorAction SilentlyContinue | Out-Null
}

# --- Create FTP root with some seed content ---
$ftpRoot = "C:\FTP\Public"
Write-Step "Creating FTP root at $ftpRoot"
if (-not (Test-Path $ftpRoot)) { New-Item -ItemType Directory -Path $ftpRoot -Force | Out-Null }

Set-Content "$ftpRoot\README.txt" @"
This is a legacy file drop share.
If you need to transfer files between systems, use the anonymous login.
Do NOT upload production data here - anyone on the network can read it.
"@ -Encoding ASCII

Set-Content "$ftpRoot\backup-schedule.txt" @"
Nightly backup schedule:
- FILE-01 -> /nightly/fs/
- MAIL-01 -> /nightly/mx/
- Credentials for backup agent: backupsvc / Winter2024!
"@ -Encoding ASCII

# --- Configure FTP site via IIS PowerShell module (available after feature install) ---
Import-Module WebAdministration -ErrorAction SilentlyContinue

$siteName = "LabFTP"
Write-Step "Configuring FTP site '$siteName' on port 21"
try {
    if (Get-WebSite -Name $siteName -ErrorAction SilentlyContinue) { Remove-WebSite -Name $siteName -ErrorAction SilentlyContinue }
    New-WebFtpSite -Name $siteName -Port 21 -PhysicalPath $ftpRoot -Force -ErrorAction SilentlyContinue | Out-Null

    # Allow anonymous
    Set-ItemProperty "IIS:\Sites\$siteName" -Name ftpServer.security.authentication.anonymousAuthentication.enabled -Value $true
    Set-ItemProperty "IIS:\Sites\$siteName" -Name ftpServer.security.authentication.basicAuthentication.enabled     -Value $true
    # No SSL required (deliberate weakness)
    Set-ItemProperty "IIS:\Sites\$siteName" -Name ftpServer.security.ssl.controlChannelPolicy -Value 0
    Set-ItemProperty "IIS:\Sites\$siteName" -Name ftpServer.security.ssl.dataChannelPolicy    -Value 0

    # Grant anonymous Read + Write (full "legacy drop" experience)
    Add-WebConfiguration "/system.ftpServer/security/authorization" -Value @{accessType="Allow";users="*";permissions=3} -PSPath IIS: -Location $siteName
} catch {
    Write-Host "IIS FTP configuration failed: $($_.Exception.Message)"
}

# --- Firewall ---
Write-Step "Opening TCP/21 + passive range 40000-40100"
New-NetFirewallRule -DisplayName "Lab-FTP-21-Allow"      -Direction Inbound -Protocol TCP -LocalPort 21           -Action Allow -Profile Any -ErrorAction SilentlyContinue | Out-Null
New-NetFirewallRule -DisplayName "Lab-FTP-Passive-Allow" -Direction Inbound -Protocol TCP -LocalPort 40000-40100  -Action Allow -Profile Any -ErrorAction SilentlyContinue | Out-Null

Start-Service "FTPSVC" -ErrorAction SilentlyContinue
Set-Service   "FTPSVC" -StartupType Automatic -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "=== ftp-anonymous complete ==="
Write-Host "FTP root  : $ftpRoot"
Write-Host "Port      : 21/TCP (anonymous read+write)"
Write-Host "SSL       : disabled"
$FTP_ANONYMOUS$,
  '["21/FTP"]'::jsonb,
  '{"init-setup"}',
  180,
  true,
  '',
  'vulnerable'
)
ON CONFLICT (slug) DO UPDATE SET
  name                  = EXCLUDED.name,
  description           = EXCLUDED.description,
  category              = EXCLUDED.category,
  difficulty            = EXCLUDED.difficulty,
  script_content        = EXCLUDED.script_content,
  services_exposed      = EXCLUDED.services_exposed,
  depends_on            = EXCLUDED.depends_on,
  estimated_runtime_sec = EXCLUDED.estimated_runtime_sec,
  is_active             = true,
  script_args           = EXCLUDED.script_args,
  script_type           = EXCLUDED.script_type;

INSERT INTO vuln_scripts (slug, name, description, category, os_target, difficulty, script_content, services_exposed, depends_on, estimated_runtime_sec, is_active, script_args, script_type) VALUES (
  'vulnerable-registry',
  'Registry Privesc Playground',
  'AlwaysInstallElevated=1 in both hives, plaintext AutoAdminLogon, Users-writable HKLM Run key ACL, silent UAC for admins, CachedLogonsCount=25 (more DCC2 hashes on disk).',
  'Privilege Escalation',
  'windows',
  'intermediate',
  $VULNERABLE_REGISTRY$$ErrorActionPreference = "Continue"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message"
}

# --- AlwaysInstallElevated (classic MSI-based privesc) ---
Write-Step "Setting AlwaysInstallElevated in HKLM and HKCU"
$paths = @(
    "HKLM:\Software\Policies\Microsoft\Windows\Installer",
    "HKCU:\Software\Policies\Microsoft\Windows\Installer"
)
foreach ($p in $paths) {
    if (-not (Test-Path $p)) { New-Item -Path $p -Force | Out-Null }
    New-ItemProperty -Path $p -Name "AlwaysInstallElevated" -PropertyType DWord -Value 1 -Force | Out-Null
}

# --- Auto-logon (plaintext credentials in the registry) ---
Write-Step "Configuring AutoAdminLogon with plaintext credentials"
$winlogon = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon"
New-ItemProperty -Path $winlogon -Name "AutoAdminLogon"    -PropertyType String -Value "1"                  -Force | Out-Null
New-ItemProperty -Path $winlogon -Name "DefaultUserName"   -PropertyType String -Value "Administrator"       -Force | Out-Null
New-ItemProperty -Path $winlogon -Name "DefaultPassword"   -PropertyType String -Value "Autumn2024!Admin"   -Force | Out-Null
New-ItemProperty -Path $winlogon -Name "DefaultDomainName" -PropertyType String -Value $env:COMPUTERNAME     -Force | Out-Null

# --- Writable autorun key for low-priv users (Users can drop a payload) ---
Write-Step "Weakening ACL on HKLM Run key (Users:Write)"
$runKey = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run"
try {
    $acl = Get-Acl $runKey
    $rule = New-Object System.Security.AccessControl.RegistryAccessRule("Users","FullControl","ContainerInherit,ObjectInherit","None","Allow")
    $acl.AddAccessRule($rule)
    Set-Acl -Path $runKey -AclObject $acl
} catch { Write-Host "ACL tweak on Run key failed: $($_.Exception.Message)" }

# --- UAC bypass aids: disable prompt for admins, disable secure desktop ---
Write-Step "Weakening UAC (ConsentPromptBehaviorAdmin=0, PromptOnSecureDesktop=0)"
$sys = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"
New-ItemProperty -Path $sys -Name "ConsentPromptBehaviorAdmin" -PropertyType DWord -Value 0 -Force | Out-Null
New-ItemProperty -Path $sys -Name "PromptOnSecureDesktop"      -PropertyType DWord -Value 0 -Force | Out-Null
# EnableLUA stays at 1 so the box still looks "UAC-enabled" in a cursory check, but prompts are silent for admins.

# --- Cached interactive logons (DCC2 hashes extractable offline) ---
Write-Step "Setting CachedLogonsCount=25 (leaves more DCC2 hashes on disk)"
New-ItemProperty -Path $winlogon -Name "CachedLogonsCount" -PropertyType String -Value "25" -Force | Out-Null

Write-Host ""
Write-Host "=== vulnerable-registry complete ==="
Write-Host "AlwaysInstallElevated : 1 (both hives)"
Write-Host "AutoAdminLogon        : plaintext creds stored"
Write-Host "UAC prompts           : silent for admins"
Write-Host "Run key ACL           : Users:Write"
$VULNERABLE_REGISTRY$,
  '[]'::jsonb,
  '{"init-setup"}',
  15,
  true,
  '',
  'vulnerable'
)
ON CONFLICT (slug) DO UPDATE SET
  name                  = EXCLUDED.name,
  description           = EXCLUDED.description,
  category              = EXCLUDED.category,
  difficulty            = EXCLUDED.difficulty,
  script_content        = EXCLUDED.script_content,
  services_exposed      = EXCLUDED.services_exposed,
  depends_on            = EXCLUDED.depends_on,
  estimated_runtime_sec = EXCLUDED.estimated_runtime_sec,
  is_active             = true,
  script_args           = EXCLUDED.script_args,
  script_type           = EXCLUDED.script_type;

INSERT INTO vuln_scripts (slug, name, description, category, os_target, difficulty, script_content, services_exposed, depends_on, estimated_runtime_sec, is_active, script_args, script_type) VALUES (
  'cached-credentials',
  'Plaintext Credentials Hunt',
  'Seeds credential artifacts in six common places: unattend.xml (Panther), GPP Groups.xml cpassword, nightly-backup.bat net-use, WinSCP.ini, machine-level DB_PASSWORD env var, PSReadLine history with embedded creds.',
  'Credential Access',
  'windows',
  'beginner',
  $CACHED_CREDENTIALS$$ErrorActionPreference = "Continue"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message"
}

# --- unattend.xml with plaintext credentials ---
Write-Step "Seeding unattend.xml with plaintext credentials"
$pantherDir = "C:\Windows\Panther"
if (-not (Test-Path $pantherDir)) { New-Item -ItemType Directory -Path $pantherDir -Force | Out-Null }

$unattend = @'
<?xml version="1.0" encoding="utf-8"?>
<unattend xmlns="urn:schemas-microsoft-com:unattend">
  <settings pass="specialize">
    <component name="Microsoft-Windows-Shell-Setup">
      <AutoLogon>
        <Password>
          <Value>Winter2024!Deploy</Value>
          <PlainText>true</PlainText>
        </Password>
        <Enabled>true</Enabled>
        <LogonCount>3</LogonCount>
        <Username>deploy</Username>
      </AutoLogon>
      <UserAccounts>
        <AdministratorPassword>
          <Value>Admin2024!</Value>
          <PlainText>true</PlainText>
        </AdministratorPassword>
      </UserAccounts>
    </component>
  </settings>
</unattend>
'@
Set-Content "$pantherDir\unattend.xml" $unattend -Encoding UTF8

# --- Group Policy Preferences (cpassword -- the classic) ---
Write-Step "Seeding GPP cpassword in SYSVOL-style path"
$gppDir = "C:\ProgramData\LabGPP\Groups"
New-Item -ItemType Directory -Path $gppDir -Force | Out-Null
# cpassword below decrypts to "Password123" via the well-known AES key (MS14-025 era).
Set-Content "$gppDir\Groups.xml" @'
<?xml version="1.0" encoding="utf-8"?>
<Groups clsid="{3125E937-EB16-4b4c-9934-544FC6D24D26}">
  <User clsid="{DF5F1855-51E5-4d24-8B1A-D9BDE98BA1D1}"
        name="labadmin"
        image="2" changed="2024-08-12 14:00:00"
        uid="{AA3C5F58-12B4-42A9-A07F-CE4F62F1D2B1}">
    <Properties action="U"
                newName=""
                fullName="Lab Admin"
                description=""
                cpassword="j1Uyj3Vx8TY9LtLZil2uAuZkFQA/4latT76ZwgdHdhw"
                changeLogon="0" noChange="1" neverExpires="1"
                acctDisabled="0" userName="labadmin"/>
  </User>
</Groups>
'@ -Encoding UTF8

# --- Plaintext creds in a nightly-backup .bat (common admin laziness pattern) ---
Write-Step "Seeding backup .bat with net-use credentials"
$scriptsDir = "C:\Scripts"
if (-not (Test-Path $scriptsDir)) { New-Item -ItemType Directory -Path $scriptsDir -Force | Out-Null }
Set-Content "$scriptsDir\nightly-backup.bat" @"
@echo off
REM Nightly backup -- last edited by msp-tech on 2024-08-02
net use Z: \\backup01\nightly /user:BACKUPSVC Autumn2024!Backup /persistent:no
robocopy C:\Data Z:\data /MIR /R:2 /W:5 > C:\Lab\logs\nightly-backup.log 2>&1
net use Z: /delete
"@ -Encoding ASCII
icacls "$scriptsDir\nightly-backup.bat" /grant "Users:(R)" | Out-Null

# --- WinSCP-style saved session file (base64-ish encoded password) ---
Write-Step "Seeding WinSCP.ini with saved session"
$winscpDir = "C:\Users\Public\Documents"
Set-Content "$winscpDir\WinSCP.ini" @"
[Sessions]
[Sessions\sftp%5Ffiles]
HostName=files.internal.lab
UserName=msp-tech
PortNumber=22
Password=A35C7D81E9B2F4A6C8D0E1F20304050607
Protocol=2
"@ -Encoding UTF8

# --- Environment variable with "password" -- some tools grep env for this ---
Write-Step "Setting machine-level env var DB_PASSWORD"
[Environment]::SetEnvironmentVariable("DB_PASSWORD", "Winter2024!DB", "Machine")

# --- PowerShell history with a clear-text credential (AllUsersAllHosts) ---
Write-Step "Seeding PSReadLine history with embedded password"
$psHistory = "$env:APPDATA\..\..\..\Users\student\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine"
if (-not (Test-Path $psHistory)) { New-Item -ItemType Directory -Path $psHistory -Force | Out-Null }
Set-Content "$psHistory\ConsoleHost_history.txt" @"
Get-Service
ipconfig /all
net use \\fileserver\backups /user:BACKUPSVC Autumn2024!Backup
whoami /all
Get-ADUser -Filter * | Select Name
"@ -Encoding ASCII

Write-Host ""
Write-Host "=== cached-credentials complete ==="
Write-Host "unattend.xml    : C:\Windows\Panther\unattend.xml (Admin2024!)"
Write-Host "Groups.xml      : cpassword -> Password123"
Write-Host "nightly-backup  : C:\Scripts\nightly-backup.bat (Autumn2024!Backup)"
Write-Host "WinSCP.ini      : C:\Users\Public\Documents\WinSCP.ini"
Write-Host "env DB_PASSWORD : Winter2024!DB"
Write-Host "PSReadLine      : student history"
$CACHED_CREDENTIALS$,
  '[]'::jsonb,
  '{"init-setup"}',
  10,
  true,
  '',
  'vulnerable'
)
ON CONFLICT (slug) DO UPDATE SET
  name                  = EXCLUDED.name,
  description           = EXCLUDED.description,
  category              = EXCLUDED.category,
  difficulty            = EXCLUDED.difficulty,
  script_content        = EXCLUDED.script_content,
  services_exposed      = EXCLUDED.services_exposed,
  depends_on            = EXCLUDED.depends_on,
  estimated_runtime_sec = EXCLUDED.estimated_runtime_sec,
  is_active             = true,
  script_args           = EXCLUDED.script_args,
  script_type           = EXCLUDED.script_type;

INSERT INTO vuln_scripts (slug, name, description, category, os_target, difficulty, script_content, services_exposed, depends_on, estimated_runtime_sec, is_active, script_args, script_type) VALUES (
  'defender-weaken',
  'Defender Downgrade',
  'Path / extension / process exclusions for lab folders, disables real-time + behavior + script + archive scanning, disables PUA + cloud sampling. Retains Defender presence so the box still looks protected on a cursory check.',
  'Defense Evasion',
  'windows',
  'beginner',
  $DEFENDER_WEAKEN$$ErrorActionPreference = "Continue"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message"
}

# --- Add broad path exclusions so lab artifacts + common tool drop paths don't get quarantined ---
Write-Step "Adding Defender path exclusions for lab folders"
$excludePaths = @(
    "C:\Lab",
    "C:\LabApps",
    "C:\LabShare",
    "C:\Tools",
    "C:\Scripts",
    "C:\Users\Public\Downloads",
    "C:\Users\student\Downloads"
)
foreach ($p in $excludePaths) {
    Add-MpPreference -ExclusionPath $p -ErrorAction SilentlyContinue
}

# --- Exclude common extension patterns used in CTF exercises ---
Write-Step "Adding file-extension exclusions"
foreach ($ext in @(".ps1",".hta",".bat",".cmd",".py",".exe")) {
    Add-MpPreference -ExclusionExtension $ext -ErrorAction SilentlyContinue
}

# --- Exclude processes commonly invoked in post-exploitation ---
Write-Step "Adding process exclusions"
foreach ($proc in @("powershell.exe","cmd.exe","cscript.exe","wscript.exe","mshta.exe","rundll32.exe")) {
    Add-MpPreference -ExclusionProcess $proc -ErrorAction SilentlyContinue
}

# --- Lower the bar: disable cloud-delivered protection + sample submission ---
Write-Step "Disabling cloud protection + auto sample submission"
Set-MpPreference -MAPSReporting Disabled                 -ErrorAction SilentlyContinue
Set-MpPreference -SubmitSamplesConsent NeverSend         -ErrorAction SilentlyContinue
Set-MpPreference -DisableRealtimeMonitoring $true        -ErrorAction SilentlyContinue
Set-MpPreference -DisableIOAVProtection $true            -ErrorAction SilentlyContinue
Set-MpPreference -DisableBehaviorMonitoring $true        -ErrorAction SilentlyContinue
Set-MpPreference -DisableScriptScanning $true            -ErrorAction SilentlyContinue
Set-MpPreference -DisableArchiveScanning $true           -ErrorAction SilentlyContinue

# --- Shrink the reputation service's effect: Pua disabled (so would-be PUAs run) ---
Set-MpPreference -PUAProtection Disabled -ErrorAction SilentlyContinue

# --- AMSI off via registry (blue-team can still detect; this is deliberate) ---
Write-Step "Disabling AMSI provider via registry"
$amsi = "HKLM:\SOFTWARE\Microsoft\Windows Defender\Features"
if (-not (Test-Path $amsi)) { New-Item -Path $amsi -Force | Out-Null }
New-ItemProperty -Path $amsi -Name "TamperProtection" -PropertyType DWord -Value 0 -Force -ErrorAction SilentlyContinue | Out-Null

Write-Host ""
Write-Host "=== defender-weaken complete ==="
Write-Host "Paths excluded      : $($excludePaths -join ', ')"
Write-Host "Real-time           : disabled"
Write-Host "Behavior monitor    : disabled"
Write-Host "Script scan         : disabled"
Write-Host "Cloud + sampling    : disabled"
$DEFENDER_WEAKEN$,
  '[]'::jsonb,
  '{"init-setup"}',
  15,
  true,
  '',
  'vulnerable'
)
ON CONFLICT (slug) DO UPDATE SET
  name                  = EXCLUDED.name,
  description           = EXCLUDED.description,
  category              = EXCLUDED.category,
  difficulty            = EXCLUDED.difficulty,
  script_content        = EXCLUDED.script_content,
  services_exposed      = EXCLUDED.services_exposed,
  depends_on            = EXCLUDED.depends_on,
  estimated_runtime_sec = EXCLUDED.estimated_runtime_sec,
  is_active             = true,
  script_args           = EXCLUDED.script_args,
  script_type           = EXCLUDED.script_type;

INSERT INTO vuln_scripts (slug, name, description, category, os_target, difficulty, script_content, services_exposed, depends_on, estimated_runtime_sec, is_active, script_args, script_type) VALUES (
  'event-log-reduction',
  'Log Retention Minimized',
  'Shrinks Application / Security / System / Setup logs to 1MB each, disables PS script-block + module logging, disables 4688 cmdline auditing, clears existing logs, disables Sysmon if present.',
  'Defense Evasion',
  'windows',
  'intermediate',
  $EVENT_LOG_REDUCTION$$ErrorActionPreference = "Continue"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message"
}

# --- Shrink log file sizes so rotation destroys forensic evidence quickly ---
Write-Step "Shrinking Application/Security/System logs to 1MB each"
foreach ($log in @("Application","Security","System","Setup")) {
    try {
        wevtutil sl $log /ms:1048576 /rt:false /ab:false 2>$null
    } catch {}
}

# --- Disable PowerShell script-block + module logging (evasion) ---
Write-Step "Disabling PowerShell module + script-block logging"
$psLog = "HKLM:\Software\Policies\Microsoft\Windows\PowerShell"
if (-not (Test-Path $psLog))                         { New-Item -Path $psLog -Force | Out-Null }
if (-not (Test-Path "$psLog\ScriptBlockLogging"))    { New-Item -Path "$psLog\ScriptBlockLogging" -Force | Out-Null }
if (-not (Test-Path "$psLog\ModuleLogging"))         { New-Item -Path "$psLog\ModuleLogging"      -Force | Out-Null }
New-ItemProperty -Path "$psLog\ScriptBlockLogging" -Name "EnableScriptBlockLogging"              -PropertyType DWord -Value 0 -Force | Out-Null
New-ItemProperty -Path "$psLog\ScriptBlockLogging" -Name "EnableScriptBlockInvocationLogging"    -PropertyType DWord -Value 0 -Force | Out-Null
New-ItemProperty -Path "$psLog\ModuleLogging"      -Name "EnableModuleLogging"                   -PropertyType DWord -Value 0 -Force | Out-Null

# --- Disable command-line process auditing ---
Write-Step "Disabling 4688 command-line auditing"
$cmdAudit = "HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Audit"
if (-not (Test-Path $cmdAudit)) { New-Item -Path $cmdAudit -Force | Out-Null }
New-ItemProperty -Path $cmdAudit -Name "ProcessCreationIncludeCmdLine_Enabled" -PropertyType DWord -Value 0 -Force | Out-Null

# --- Clear existing logs so students start with nothing to pivot off of ---
Write-Step "Clearing existing logs (Application/Security/System/Windows PowerShell)"
foreach ($log in @("Application","Security","System","Windows PowerShell")) {
    try { wevtutil cl $log 2>$null } catch {}
}

# --- Disable Sysmon if present (service name may or may not exist) ---
$sysmon = Get-Service -Name "Sysmon*" -ErrorAction SilentlyContinue
if ($sysmon) {
    Write-Step "Disabling Sysmon service"
    foreach ($s in $sysmon) { Stop-Service $s -Force -ErrorAction SilentlyContinue; Set-Service $s -StartupType Disabled -ErrorAction SilentlyContinue }
}

Write-Host ""
Write-Host "=== event-log-reduction complete ==="
Write-Host "Log sizes         : 1MB each (rotation destroys ~30s of activity)"
Write-Host "Script-block log  : disabled"
Write-Host "Module log        : disabled"
Write-Host "4688 cmdline      : disabled"
Write-Host "Existing logs     : cleared"
$EVENT_LOG_REDUCTION$,
  '[]'::jsonb,
  '{"init-setup"}',
  15,
  true,
  '',
  'vulnerable'
)
ON CONFLICT (slug) DO UPDATE SET
  name                  = EXCLUDED.name,
  description           = EXCLUDED.description,
  category              = EXCLUDED.category,
  difficulty            = EXCLUDED.difficulty,
  script_content        = EXCLUDED.script_content,
  services_exposed      = EXCLUDED.services_exposed,
  depends_on            = EXCLUDED.depends_on,
  estimated_runtime_sec = EXCLUDED.estimated_runtime_sec,
  is_active             = true,
  script_args           = EXCLUDED.script_args,
  script_type           = EXCLUDED.script_type;

INSERT INTO vuln_scripts (slug, name, description, category, os_target, difficulty, script_content, services_exposed, depends_on, estimated_runtime_sec, is_active, script_args, script_type) VALUES (
  'scheduled-task-privesc',
  'Writable Scheduled Tasks',
  'Two SYSTEM scheduled tasks (LabHealthCheck every 15m, LabDeploy at logon) backed by Users-writable script and .bat files for classic task-hijack privesc; grants Users read on the Tasks folder for enumeration.',
  'Privilege Escalation',
  'windows',
  'intermediate',
  $SCHEDULED_TASK_PRIVESC$$ErrorActionPreference = "Continue"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message"
}

# --- 1. A SYSTEM task whose XML definition is Users-writable ---
Write-Step "Creating SYSTEM task 'LabHealthCheck' with a writable task XML"
$taskFolder = "C:\ProgramData\LabOps"
if (-not (Test-Path $taskFolder)) { New-Item -ItemType Directory -Path $taskFolder -Force | Out-Null }

$healthScript = "$taskFolder\health-check.ps1"
Set-Content $healthScript @'
# Hourly health check - just pings internal services
Test-NetConnection -ComputerName 127.0.0.1 -Port 80 -InformationLevel Quiet | Out-Null
Write-Output "[$(Get-Date)] health check ok"
'@ -Encoding UTF8

# Make the SCRIPT writable by Users - classic privesc: replace contents, wait for next tick
icacls $healthScript /grant "Users:(F)" | Out-Null

$action    = New-ScheduledTaskAction    -Execute "powershell.exe" -Argument "-ExecutionPolicy Bypass -File `"$healthScript`""
$trigger   = New-ScheduledTaskTrigger   -Once -At (Get-Date).AddMinutes(5) -RepetitionInterval (New-TimeSpan -Minutes 15) -RepetitionDuration ([TimeSpan]::MaxValue)
$principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest
$settings  = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries
Register-ScheduledTask -TaskName "LabHealthCheck" -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Force | Out-Null

# --- 2. A Users task that calls into C:\ProgramData\Deploy\deploy.bat (also Users-writable) ---
Write-Step "Creating interactive-user task 'LabDeploy' with Users-writable .bat"
$deployDir = "C:\ProgramData\Deploy"
if (-not (Test-Path $deployDir)) { New-Item -ItemType Directory -Path $deployDir -Force | Out-Null }
Set-Content "$deployDir\deploy.bat" "@echo off`r`necho Deploy stub.`r`nexit /b 0" -Encoding ASCII
icacls "$deployDir"            /grant "Users:(OI)(CI)M" | Out-Null
icacls "$deployDir\deploy.bat" /grant "Users:(F)"       | Out-Null

$dpAction  = New-ScheduledTaskAction -Execute "$deployDir\deploy.bat"
$dpTrigger = New-ScheduledTaskTrigger -AtLogOn
$dpPrinc   = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest
Register-ScheduledTask -TaskName "LabDeploy" -Action $dpAction -Trigger $dpTrigger -Principal $dpPrinc -Force | Out-Null

# --- 3. Ensure Users can list and read task definitions (so enumeration works) ---
Write-Step "Granting Users read on Tasks folder"
icacls "C:\Windows\System32\Tasks" /grant "Users:(OI)(CI)R" /T 2>$null | Out-Null

Write-Host ""
Write-Host "=== scheduled-task-privesc complete ==="
Write-Host "Task: LabHealthCheck (SYSTEM, every 15m)  -> $healthScript (Users:F)"
Write-Host "Task: LabDeploy      (SYSTEM, at logon)   -> $deployDir\deploy.bat (Users:F)"
$SCHEDULED_TASK_PRIVESC$,
  '[]'::jsonb,
  '{"init-setup"}',
  15,
  true,
  '',
  'vulnerable'
)
ON CONFLICT (slug) DO UPDATE SET
  name                  = EXCLUDED.name,
  description           = EXCLUDED.description,
  category              = EXCLUDED.category,
  difficulty            = EXCLUDED.difficulty,
  script_content        = EXCLUDED.script_content,
  services_exposed      = EXCLUDED.services_exposed,
  depends_on            = EXCLUDED.depends_on,
  estimated_runtime_sec = EXCLUDED.estimated_runtime_sec,
  is_active             = true,
  script_args           = EXCLUDED.script_args,
  script_type           = EXCLUDED.script_type;

COMMIT;
