variable "proxmox_url" {
    type        = string
    description = "Proxmox API endpoint, e.g. https://pve.example.com:8006/api2/json"
    }

variable "proxmox_username" {
    type        = string
    description = "API token ID, e.g. packer@pve!packer-token"
    }

variable "proxmox_token" {
    type        = string
    sensitive   = true
    description = "API token secret, e.g. 7d8a6a89-f94e-4fb0-95c5-12812e1ab4c8"
    }

variable "proxmox_node" {
    type        = string
    description = "Proxmox node, e.g. pve-node-0"
    }

variable "iso_storage_pool" {
    type        = string
    description = "Storage pool for ISO files, e.g. cephfs"
    }

variable "disk_storage_pool" {
    type        = string
    description = "Storage pool for disk images, e.g. vmpool"
    }

variable "vm_id" {
    type        = number
    description = "ID of the VM to be created"
    }

variable "template_name" {
    type        = string
    description = "Name of the template to be created"
    }

variable "kali_iso" {
    type        = string
    description = "Proxmox volume ID of the Kali installer ISO, e.g. cephfs:iso/kali-linux-2025.4-installer-amd64.iso"
    }

# Kali reshuffles ISOs on mirrors, so a pinned checksum is worth having. Use
# "none" to skip verification, or the value from the release's SHA256SUMS file
# as "sha256:<hex>". Packer accepts a URL here too:
#   "file:https://cdimage.kali.org/kali-2025.4/SHA256SUMS"
variable "kali_iso_checksum" {
    type        = string
    default     = "none"
    description = "Checksum of the Kali ISO, e.g. sha256:abc123... or \"none\""
    }

variable "cores" {
    type        = number
    description = "Number of CPU cores to allocate to the VM"
    }

variable "memory" {
    type        = number
    description = "Amount of memory to allocate to the VM (in MB)"
    }

variable "disk_size" {
    type        = string
    description = "Size of the disk to allocate to the VM, e.g. 64G"
    }

variable "network_bridge" {
    type        = string
    description = "Network bridge to connect the VM to, e.g. vmbr0"
    }

variable "vlan_tag" {
    type        = string
    description = "VLAN tag to use for the VM, e.g. 60. Must have outbound HTTPS -- the installer pulls from http.kali.org."
    }

variable "timezone" {
    type        = string
    description = "Timezone for the VM, e.g. UTC"
    }

variable "locale" {
    type        = string
    default     = "en_US.UTF-8"
    description = "System locale generated by the installer"
    }

variable "keyboard_layout" {
    type        = string
    default     = "us"
    description = "X keymap, e.g. us"
    }

# This account SURVIVES into the template. It is both the account Packer
# authenticates with during the build and the fallback login on a clone.
#
# Per-clone credentials come from Proxmox's Cloud-Init ciuser/cipassword
# fields, which create a SEPARATE account on first boot -- unlike the Windows
# template, where Cloudbase-Init resets the build account's password. Keeping
# this one named `kali` matches the cloud-image lineage that
# front-end/scripts/bake-kali-template.sh produces, so lane tooling that
# assumes a `kali` user keeps working either way.
variable "ssh_username" {
    type        = string
    default     = "kali"
    description = "Account created by the preseed and kept in the template. Packer's SSH user."
    }

# Build-time password. It is served over plain HTTP inside the preseed and
# stored unhashed in this repo's vars file, so treat it as disposable: it is
# only reachable from the build VLAN and only until the template is sealed.
variable "ssh_password" {
    type        = string
    sensitive   = true
    description = "Password for ssh_username. Build-time credential -- keep it disposable."
    }

# 'minimal' = xfce + xrdp only (~4GB).
# 'default' = kali-linux-default metapackage (~12GB, the common pentest tools).
# 'large'   = kali-linux-large (everything, ~25GB, adds ~30 min to the build).
variable "kali_toolset" {
    type        = string
    default     = "default"
    description = "Which Kali metapackage to install: minimal | default | large"

    validation {
        condition     = contains(["minimal", "default", "large"], var.kali_toolset)
        error_message = "The kali_toolset variable must be one of: minimal, default, large."
    }
    }

variable "kali_mirror_host" {
    type        = string
    default     = "http.kali.org"
    description = "Debian-installer mirror hostname. Point at a local mirror if the build VLAN has one."
    }

variable "kali_mirror_directory" {
    type        = string
    default     = "/kali"
    description = "Path on kali_mirror_host, e.g. /kali"
    }

variable "apt_proxy" {
    type        = string
    default     = ""
    description = "Optional apt proxy used during the build only, e.g. http://apt-cache.lab:3142. Removed before seal."
    }

# The build VM fetches the preseed from an HTTP server Packer runs on the
# machine invoking `packer build`. That machine must be reachable from
# vlan_tag. Pin the address when the operator host is multi-homed and Packer
# guesses the wrong interface.
variable "http_bind_address" {
    type        = string
    default     = "0.0.0.0"
    description = "Address Packer's preseed HTTP server binds to"
    }

variable "http_port_min" {
    type        = number
    default     = 8600
    description = "Low end of the preseed HTTP server port range (open this in any host firewall)"
    }

variable "http_port_max" {
    type        = number
    default     = 8610
    description = "High end of the preseed HTTP server port range"
    }
