#!/usr/bin/env python3
"""Regenerate the standalone Bash/Python pasteable from its Python source."""
from pathlib import Path


def content():
    source = Path(__file__).with_name("install_lane_soc.py").read_text(encoding="utf-8")
    return """#!/usr/bin/env bash
# Generated by build_pasteable.py. Copy this ENTIRE file into a Bash terminal
# on the lane ELK VM, or run: bash install-lane-soc.sh [installer arguments]
# Requires Python 3.8+. Default endpoints are local :5601 and :9200.
# Read scripts/lane-elk/README.md for credentials, spaces and detection limits.
(
set -eu
command -v python3 >/dev/null || { echo 'Python 3.8+ is required.' >&2; exit 1; }
python3 - "$@" <<'CYBERCORE_LANE_SOC_PYTHON'
""" + source + "\nCYBERCORE_LANE_SOC_PYTHON\n)\n"


if __name__ == "__main__":
    with Path(__file__).with_name("install-lane-soc.sh").open("w", encoding="utf-8", newline="\n") as output:
        output.write(content())
